---
author:: Yuriko Archambault, Marie-Ève Gagné, Juliette Larrivée et Daphnée Longworth
title: "Réseau écologique d'étudiants de l'Université de Sherbrooke"
shorttitle: "Projet de session"
output: 
  html_document: 
    toc: yes
    highlight: tango
    theme: cerulean
    number_sections: yes
    self_contained: false
---


# Introduction

Insérer introduction ici

# Développement

## Est-ce que les étudiants interagit davantage avec ceux de leur programme?
1ere section 

```{r}
# Scrip r ici
```


## Est-ce que les étudiants interagit davantage avec ceux de leur cohorte?
2eme section

## Est-ce que les étudiants préfèrent travailler avec les mêmes étudiants?
3eme section

```{r}
#Figure 3

#collab_etudiant <- read.csv2("arbres.csv")
#paires <- table(collab_etudiant[,c(3,5)])
#frequence <- as.numeric(row.names(paires))
#plot(frequence, paires[,1], axes =TRUE,
#     xlab = "Fréquence", ylab = "Nb paires différentes qui ont collaboré ensemble")
#title(main = "Fréquence de collaboration des étudiants en fonction du nombre de paires différentes qui ont collaboré ensemble")
#usethis::git_sitrep()
```


[citation](https://econumuds.github.io/BIO500/bloc3/#43)

# Conclusion
Conclusion ici

```{r}
sessionInfo()
```


# References {-}
