
---
title: Réseau écologique des étudiants de Sherbrooke
author:
- Yuriko Archambault
- Marie-Ève Gagné
- Juliette Larrivée
- Daphnée Longworth
output:
  pdf_document: default
---

# Introduction

Texte ici

# Résultats

## Section 1

Texte ici

## Section 2

Texte ici

## Section 3

Texte ici

# Méthode

## Section 1

Texte ici

## Section 2

Texte ici

## Section 3

Texte ici

# Discussion

## Section 1

Texte ici

## Section 2

Texte ici

## Section 3

Texte ici

# Conclusion

# Bibliographie

References should be cited in numerical order as they appear in text;
this will be done automatically via bibtex, e.g. @belkin2002using and
@berard1994embedding [@coifman2005geometric]. All references, including
for the SI, should be included in the main manuscript file. References
appearing in both sections should not be duplicated. SI references
included in tables should be included with the main reference section.


# Figure et tableau

![Placeholder image of a frog with a long example caption to show
justification setting.<span data-label="fig:frog"></span>](frog.png)

Figures and Tables should be labelled and referenced in the standard way
using the `\label{}` and `\ref{}` commands.

Figure \[fig:frog\] shows an example of how to insert a column-wide
figure. To insert a figure wider than one column, please use the
`\begin{figure*}...\end{figure*}` environment. Figures wider than one
column should be sized to 11.4 cm or 17.8 cm wide.


$$\begin{aligned}
(x+y)^3&=(x+y)(x+y)^2\\
       &=(x+y)(x^2+2xy+y^2) \label{eqn:example} \\
       &=x^3+3x^2y+3xy^3+x^3. 
\end{aligned}$$
